# Generated by Django 5.1.5 on 2025-07-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="time",
            field=models.TimeField(null=True),
        ),
    ]
